In [1]:
import numpy as np
print(np.__version__)


1.26.4


In [2]:
a=np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#ndarray = np.dimensionalarray
a=np.array([(1,2,3),(4,5,6)])
print(a)


[[1 2 3]
 [4 5 6]]


In [9]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
print(np.column_stack((n1,n2)))
print(np.row_stack((n1,n2)))
print(np.sum([n1,n2]))

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
21


In [10]:
values=np.array([1,2,3])
exp_values=np.exp(values)
print(exp_values)

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
values=np.array([1.5,2.3,3.7])


In [1]:
import numpy as np

# 1-D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1-D array shape:", array_1d.shape)

# 2-D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2-D array shape:", array_2d.shape)

# 3-D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3-D array shape:", array_3d.shape)


1-D array shape: (5,)
2-D array shape: (2, 3)
3-D array shape: (2, 2, 2)


In [2]:
# Original 1-D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape into a 2x3 array
array_reshaped = array_1d.reshape((2, 3))
print("Reshaped array (2x3):")
print(array_reshaped)

# Reshape into a 3x2 array
array_reshaped_2 = array_1d.reshape((3, 2))
print("Reshaped array (3x2):")
print(array_reshaped_2)

# Reshaping into a 3-D array
array_reshaped_3d = array_1d.reshape((2, 3, 1))
print("Reshaped array (2x3x1):")
print(array_reshaped_3d)


Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
Reshaped array (3x2):
[[1 2]
 [3 4]
 [5 6]]
Reshaped array (2x3x1):
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
