In [1]:
import numpy as np
print(np.__version__)


1.26.4


In [2]:
a=np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#ndarray = np.dimensionalarray
a=np.array([(1,2,3),(4,5,6)])
print(a)


[[1 2 3]
 [4 5 6]]


In [9]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
print(np.column_stack((n1,n2)))
print(np.row_stack((n1,n2)))
print(np.sum([n1,n2]))

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
21


In [10]:
values=np.array([1,2,3])
exp_values=np.exp(values)
print(exp_values)

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
values=np.array([1.5,2.3,3.7])
rounded_values