In [1]:
import numpy as np

In [4]:
# Create two 2-D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [6]:
# Addition of two 2-D arrays
add_result = np.add(arr1, arr2)
print("\nAddition of two arrays:")
print(add_result)


Addition of two arrays:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [7]:
# Subtraction of two 2-D arrays
sub_result = np.subtract(arr1, arr2)
print("\nSubtraction of two arrays:")
print(sub_result)


Subtraction of two arrays:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [8]:

# Element-wise multiplication of two 2-D arrays
mul_result = np.multiply(arr1, arr2)
print("\nElement-wise multiplication of two arrays:")
print(mul_result)


Element-wise multiplication of two arrays:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [9]:
# Matrix multiplication of two 2-D arrays
matmul_result = np.dot(arr1, arr2)
print("\nMatrix multiplication of two arrays:")
print(matmul_result)


Matrix multiplication of two arrays:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
