In [1]:
import numpy as np

In [2]:
import numpy as np

# Create a 2-D array (matrix)
array = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

print("Original Array:")
print(array)

# Swap columns 0 and 2 (1st and 3rd columns)
array[:, [0, 2]] = array[:, [2, 0]]

print("\nArray after swapping 1st and 3rd columns:")
print(array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping 1st and 3rd columns:
[[3 2 1]
 [6 5 4]
 [9 8 7]]
